general_settings:
  database_connection_pool_limit: 20

model_list:
  - model_name: "*"
    litellm_params:
      model: "*"

litellm_settings:
  drop_params: True
  success_callback: ["prometheus"]
  failure_callback: ["prometheus"]
  service_callback: ["prometheus_system"]

