general_settings:
  database_connection_pool_limit: 20

model_list:
  - model_name: "*"
    litellm_params:
      model: "*"
  - model_name: "misanthropic/*"
    litellm_params:
      model: "anthropic/*"
  - model_name: "openai/maude-3.5"
    litellm_params:
      model: "anthropic/claude-3-5-sonnet-20241022"
  - model_name: "openai/maude-3.7"
    litellm_params:
      model: "anthropic/claude-3-7-sonnet-20250219"

litellm_settings:
  drop_params: true
  set_verbose: false
  turn_off_message_logging: false
  success_callback: ["langfuse"]
  failure_callback: ["langfuse"]

