general_settings:
  database_connection_pool_limit: 20

model_list:
  - model_name: "*"
    litellm_params:
      model: "*"
 - model_name: "misanthropic/*"
   litellm_params:
      model: "anthropic/*"
 - model_name: "perplexed/*"
   litellm_params:
      model: "perplexity/*"
  - model_name: "the-butler"
    litellm_params:
      model: "anthropic/claude-3-5-sonnet-20241022"

litellm_settings:
  drop_params: True
  set_verbose: true
  success_callback: ["langfuse"]
  failure_callback: ["langfuse"]

